# BEGIN_KITTY_THEME
# Doom One
include current-theme.conf
# END_KITTY_THEME

background_opacity 1

TERM=xterm-kitty-256color

# error bell
enable_audio_bell no

# FONTS

# font_family	        MesloLGS Nerd Font
font_family         SFMono Nerd Font
# font family         JetBrains Mono NL
italic_font         auto
bolt_font           auto
bolt_italic_font    auto

font_size 13.0

modify_font underline_thickness 150%

# CURSOR
cursor_blink_interval   0.75

cursor_stop_blinking_after  5.0

mouse_hide_wait 0.5

# TABS
tab_bar_style slant

# WINDOWS
