# Set 24-bit color
set-option -sa terminal-overrides ",xterm*:Tc"

# Mouse support
set -g mouse on

# Number windows and panes from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Change prefix to C-space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Unbind Tab
unbind -n Tab

# Shift Alt n and j to cycle through windows
bind -n M-N previous-window
bind -n M-E previous-window

# Open panes in current directory
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# Plugins
# Prefix + I = install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'  # These are customized in my nvim init.lua
set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
# Catppuccin theme flavor
set -g @catppuccin_flavour 'macchiato'

run '~/.tmux/plugins/tpm/tpm'
