[theme]

background = "#282c34"
primary = "#bbc2cf"
secondary = "5B6268"
title = "5699AF"
playing = "#4db5bd"
playing_selected = "#4db5bd"
playing_bg = "#21242b"
highlight = "#DFDFDF"
highlight_bg = "#1c1f24"
error = "#DFDFDF"
error_bg = "#ff6c6b"
statusbar = "#282c34"
statusbar_progress = "#98be65"
statusbar_bg = "#4db5bd"
cmdline = "#5B6268"
cmdline_bg = "#21242b"
search_match = "#c678dd"
